# Generated by Django 4.0.6 on 2022-07-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_mobiles_alter_blogs_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiles',
            old_name='processer',
            new_name='processor',
        ),
    ]
