# Generated by Django 4.0.6 on 2022-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0006_alter_reviews_rating_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('incart', 'incart'), ('order-placed', 'order-placed'), ('cancelled', 'cancelled')], default='incart', max_length=100),
        ),
    ]
